// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAriQ29zlni2aogwB_Ys4PmancEo4vFzw4',
    appId: '1:717493651190:web:4c6c93171a128a99994ed7',
    messagingSenderId: '717493651190',
    projectId: 'gtelerp',
    authDomain: 'gtelerp.firebaseapp.com',
    storageBucket: 'gtelerp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj1I_bndL58_sYsfCqzg7hrC3-yWF9vqk',
    appId: '1:717493651190:android:77edc8b795a6d32b994ed7',
    messagingSenderId: '717493651190',
    projectId: 'gtelerp',
    storageBucket: 'gtelerp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLJyaycjb7PyV68ixaNLygvNQBUL0deSo',
    appId: '1:717493651190:ios:245779c29caa1727994ed7',
    messagingSenderId: '717493651190',
    projectId: 'gtelerp',
    storageBucket: 'gtelerp.firebasestorage.app',
    iosBundleId: 'com.example.gtelErp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLJyaycjb7PyV68ixaNLygvNQBUL0deSo',
    appId: '1:717493651190:ios:245779c29caa1727994ed7',
    messagingSenderId: '717493651190',
    projectId: 'gtelerp',
    storageBucket: 'gtelerp.firebasestorage.app',
    iosBundleId: 'com.example.gtelErp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAriQ29zlni2aogwB_Ys4PmancEo4vFzw4',
    appId: '1:717493651190:web:a6f4446741f578d0994ed7',
    messagingSenderId: '717493651190',
    projectId: 'gtelerp',
    authDomain: 'gtelerp.firebaseapp.com',
    storageBucket: 'gtelerp.firebasestorage.app',
  );
}
